;Date: 2026/04/20 11:46:04
;Description: Parser for basic description
;Generated with compiler.lisp

(defun C_any(tokens i v)
   (check (< (car i) (size tokens))
      (setq w (@ tokens (car i)))
      (check (neq w ";") 
         (+= i 1)
         (push v w)
         (return true)
      )
   )
)

(defun compare (tokens value i v keep)
   (check 
      (and
         (< (car i) (size tokens))      
         (eq (lower (@ tokens (car i))) (lower value))
      )
      (+= i 1)
      (if keep
         (push v value)
      )
      (return true)
   )
)

(setq pythonmode false)
(link "True" true)
(link "False" nil)
(link "None" nil)

(defun C_Pythonjoin (tokens i v)
   (check (< (car i) (size tokens))
      (setq w (@ tokens (car i)))
      (check 
         (and pythonmode
            (= w "join"))
         (+= i 1)
         (return true)))
)

(defun C_Word (tokens i v)
   (check (< (car i) (size tokens))
      (setq w (@ tokens (car i)))
      (check 
         (and
            (rgx "{%a%h}{%a%h%d_@}*" w)
            (nokeywords w)
         )
         (+= i 1)
         (push v w)
         (return true)
      )
   )
)

(defun C_lispe(tokens i v)
   (check (< (car i) (size tokens))
      (setq m (@ tokens (car i)))
      (check 
            (and
               (eq (@ m 0) "`")
               (eq (@ m -1) "`")
            )
         (+= i 1)
         (push v (list 'lispexp (@@ m 1 -1)))
         (return true)
      )
   )
)

(defun C_astring(tokens i v)
   (check (< (car i) (size tokens))
      (setq m (@ tokens (car i)))
      (check 
            (and
               (eq (@ m 0) "f")
               (eq (@ m 1) "\"")
               (eq (@ m -1) "\"")
            )
         (+= i 1)
         (push v (list 'f_ (list 'string (@@ m 2 -1))))
         (return true)
      )
      (check 
            (and
               (eq (@@ m 0 3) "\"\"\"")
               (eq (@@ m -3 0) "\"\"\"")
            )
         (+= i 1)
         (push v (list 'longstring (@@ m 3 -3)))
         (return true)
      )
      (check 
            (and
               (eq (@@ m 0 3) "'''")
               (eq (@@ m -3 0) "'''")
            )
         (+= i 1)
         (push v (list 'longstring (@@ m 3 -3)))
         (return true)
      )
      (check 
            (and
               (eq (@ m 0) "\"")
               (eq (@ m -1) "\"")
            )
         (+= i 1)
         (push v (list 'string (@@ m 1 -1)))
         (return true)
      )
      (check 
            (and
               (eq (@ m 0) "'")
               (eq (@ m -1) "'")
            )
         (+= i 1)
         (push v (list 'string (@@ m 1 -1)))
         (return true)
      )
   )
)


(defun C_anumber (tokens i v)
   (check (< (car i) (size tokens))
      (setq w (@ tokens (car i)))
      (check ( (or (= w "0") (integer w) (number w)))
         (+= i 1)
         (push v (list 'anumber (float w)))
         (return true)
      )
   )
)

;°analyse := [classedef^jsfunc^jsrule^function^athread^rule^patternrule^jspatternrule^expressions]+ (entry point)
(defun C_analyse (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (P_analyse_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (cons 'analyse v0)
      )
   )
)

(defun P_analyse_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (or
         (C_classedef tokens i1 v1)
         (C_jsfunc tokens i1 v1)
         (C_jsrule tokens i1 v1)
         (C_function tokens i1 v1)
         (C_athread tokens i1 v1)
         (C_rule tokens i1 v1)
         (C_patternrule tokens i1 v1)
         (C_jspatternrule tokens i1 v1)
         (C_expressions tokens i1 v1)
      )
      (push v v1)
      (setq v1 ())
      (while (or
            (C_classedef tokens i1 v1)
            (C_jsfunc tokens i1 v1)
            (C_jsrule tokens i1 v1)
            (C_function tokens i1 v1)
            (C_athread tokens i1 v1)
            (C_rule tokens i1 v1)
            (C_patternrule tokens i1 v1)
            (C_jspatternrule tokens i1 v1)
            (C_expressions tokens i1 v1)
         )
         (nconc v v1)
         (setq v1 ())
      )
   )
   (if v
      (nconc vp v)
   )
)

(link "append" 'push)
(link "len" 'size)
(link "strip" 'trim)
;operator := [%< %<]^[%> %>]^[%^ %^]^[%* %*]^%&^%|^%+^%-^%*^%/^%%^%^
(defun C_operator (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "<" i1 v1 true)
               (compare tokens "<" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens ">" i1 v1 true)
               (compare tokens ">" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "^" i1 v1 true)
               (compare tokens "^" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "*" i1 v1 true)
               (compare tokens "*" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (compare tokens "&" i0 v0 true)
            (compare tokens "|" i0 v0 true)
            (compare tokens "+" i0 v0 true)
            (compare tokens "-" i0 v0 true)
            (compare tokens "*" i0 v0 true)
            (compare tokens "/" i0 v0 true)
            (compare tokens "%" i0 v0 true)
            (compare tokens "^" i0 v0 true)
         )
         (push v (cons 'operator v0))
      )
   )
)

;operatorop := [%< %< %=]^[%> %> %=]^[%^ %^ %=]^[%* %* %=]^[%& %=]^[%| %=]^[%+ %=]^[%- %=]^[%* %=]^[%/ %=]^[%% %=]^[%^ %=]
(defun C_operatorop (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "<" i1 v1 true)
               (compare tokens "<" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens ">" i1 v1 true)
               (compare tokens ">" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "^" i1 v1 true)
               (compare tokens "^" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "*" i1 v1 true)
               (compare tokens "*" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "&" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "|" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "+" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "-" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "*" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "/" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "%" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "^" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
         )
         (push v (cons 'operatorop v0))
      )
   )
)

;orand := $or^$and^$xor
(defun C_orand (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (compare tokens "or" i0 v0 true)
            (compare tokens "and" i0 v0 true)
            (compare tokens "xor" i0 v0 true)
         )
         (push v (cons 'orand v0))
      )
   )
)

;comparator := [%< %>]^[%! %=]^[%< %=]^[%= %=]^[%> %=]^%<^%>^$in^$eq^$neq
(defun C_comparator (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "<" i1 v1 true)
               (compare tokens ">" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "!" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "<" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens "=" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (and
               (setq i1 (clone i0))
               (setq v1 ())
               (compare tokens ">" i1 v1 true)
               (compare tokens "=" i1 v1 true)
               (set@ i0 0 (car i1))
               (setq v0 v1)
            )
            (compare tokens "<" i0 v0 true)
            (compare tokens ">" i0 v0 true)
            (compare tokens "in" i0 v0 true)
            (compare tokens "eq" i0 v0 true)
            (compare tokens "neq" i0 v0 true)
         )
         (push v (cons 'comparator v0))
      )
   )
)

;comparing := $not? computing [comparator computing]? [orand comparison]*
(defun C_comparing (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (O_comparing_0 tokens i1 v1)
            (C_computing tokens i1 v1)
            (O_comparing_1 tokens i1 v1)
            (S_comparing_2 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'comparing v0))
      )
   )
)

(defun O_comparing_0 (tokens i1 vp)
   (setq v1 ())
   (check (compare tokens "not" i1 v1 true)
      (nconc vp v1)
   )
   true)

(defun O_comparing_1 (tokens i1 vp)
   (setq v1 ())
   (check (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_comparator tokens i2 v2)
         (C_computing tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc vp v1)
   )
   true)

(defun S_comparing_2 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_orand tokens i2 v2)
         (C_comparison tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;^!comppar := %( comparing %)
(defun C_comppar (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "(" i1 v1 nil)
            (C_comparing tokens i1 v1)
            (compare tokens ")" i1 v1 nil)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (nconc v v0)
      )
   )
)

;^comparison := comppar^comparing
(defun C_comparison (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (C_comppar tokens i0 v0)
            (C_comparing tokens i0 v0)
         )
         (nconc v v0)
      )
   )
)

;comparingmax := $not? computing comparator computing [orand comparisonmax]*
(defun C_comparingmax (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (O_comparingmax_0 tokens i1 v1)
            (C_computing tokens i1 v1)
            (C_comparator tokens i1 v1)
            (C_computing tokens i1 v1)
            (S_comparingmax_1 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'comparingmax v0))
      )
   )
)

(defun O_comparingmax_0 (tokens i1 vp)
   (setq v1 ())
   (check (compare tokens "not" i1 v1 true)
      (nconc vp v1)
   )
   true)

(defun S_comparingmax_1 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_orand tokens i2 v2)
         (C_comparisonmax tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;^!compparmax := %( comparing %)
(defun C_compparmax (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "(" i1 v1 nil)
            (C_comparing tokens i1 v1)
            (compare tokens ")" i1 v1 nil)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (nconc v v0)
      )
   )
)

;^comparisonmax := compparmax^comparingmax
(defun C_comparisonmax (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (C_compparmax tokens i0 v0)
            (C_comparingmax tokens i0 v0)
         )
         (nconc v v0)
      )
   )
)

;!minus := %- anumber
(defun C_minus (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "-" i1 v1 nil)
            (C_anumber tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'minus v0))
      )
   )
)

;interval := %[ computing? %: ;10 computing? %]
(defun C_interval (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 true)
            (O_interval_0 tokens i1 v1)
            (compare tokens ":" i1 v1 true)
            (push error_id 10)
            (if (and
                  (O_interval_1 tokens i1 v1)
                  (compare tokens "]" i1 v1 true)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'interval v0))
      )
   )
)

(defun O_interval_0 (tokens i1 vp)
   (setq v1 ())
   (check (C_computing tokens i1 v1)
      (nconc vp v1)
   )
   true)

(defun O_interval_1 (tokens i1 vp)
   (setq v1 ())
   (check (C_computing tokens i1 v1)
      (nconc vp v1)
   )
   true)

;!indexes := %[ ;1 computing [%, computing]* %]
(defun C_indexes (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 nil)
            (push error_id 1)
            (if (and
                  (C_computing tokens i1 v1)
                  (S_indexes_0 tokens i1 v1)
                  (compare tokens "]" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'indexes v0))
      )
   )
)

(defun S_indexes_0 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "," i2 v2 nil)
         (C_computing tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;!valuelist := %[ ;3 [ computing [%, computing]* ]? %]
(defun C_valuelist (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 nil)
            (push error_id 3)
            (if (and
                  (O_valuelist_1 tokens i1 v1)
                  (compare tokens "]" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'valuelist v0))
      )
   )
)

(defun S_valuelist_0 (tokens i2 vp)
   (setq v ())
   (while (and
         (setq i3 (clone i2))
         (setq v3 ())
         (compare tokens "," i3 v3 nil)
         (C_computing tokens i3 v3)
         (set@ i2 0 (car i3))
         (setq v2 v3)
      )
      (nconc v v2)
   )
   (check v
      (nconc vp v)
   )
   true)

(defun O_valuelist_1 (tokens i1 vp)
   (setq v1 ())
   (check (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_computing tokens i2 v2)
         (S_valuelist_0 tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc vp v1)
   )
   true)

;!itemdictionary := [astring^minus^anumber^variable] %: computing
(defun C_itemdictionary (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (C_astring tokens i1 v1)
               (C_minus tokens i1 v1)
               (C_anumber tokens i1 v1)
               (C_variable tokens i1 v1)
            )
            (compare tokens ":" i1 v1 nil)
            (C_computing tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'itemdictionary v0))
      )
   )
)

;!valuedictionary := %{ ;11 [itemdictionary [%, itemdictionary]* ]? %}
(defun C_valuedictionary (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "{" i1 v1 nil)
            (push error_id 11)
            (if (and
                  (O_valuedictionary_1 tokens i1 v1)
                  (compare tokens "}" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'valuedictionary v0))
      )
   )
)

(defun S_valuedictionary_0 (tokens i2 vp)
   (setq v ())
   (while (and
         (setq i3 (clone i2))
         (setq v3 ())
         (compare tokens "," i3 v3 nil)
         (C_itemdictionary tokens i3 v3)
         (set@ i2 0 (car i3))
         (setq v2 v3)
      )
      (nconc v v2)
   )
   (check v
      (nconc vp v)
   )
   true)

(defun O_valuedictionary_1 (tokens i1 vp)
   (setq v1 ())
   (check (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_itemdictionary tokens i2 v2)
         (S_valuedictionary_0 tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc vp v1)
   )
   true)

;!dimvariable :=  Word [interval^indexes]+
(defun C_dimvariable (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_Word tokens i1 v1)
            (P_dimvariable_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'dimvariable v0))
      )
   )
)

(defun P_dimvariable_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (or (C_interval tokens i1 v1) (C_indexes tokens i1 v1))
      (push v v1)
      (setq v1 ())
      (while (or (C_interval tokens i1 v1) (C_indexes tokens i1 v1)) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!selfvariable := $Self %. [dimvariable^Word]
(defun C_selfvariable (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Self" i1 v1 nil)
            (compare tokens "." i1 v1 nil)
            (or
               (C_dimvariable tokens i1 v1)
               (C_Word tokens i1 v1)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'selfvariable v0))
      )
   )
)

;variable := dimvariable^Word
(defun C_variable (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (C_dimvariable tokens i0 v0)
            (C_Word tokens i0 v0)
         )
         (push v (cons 'variable v0))
      )
   )
)

;!variables := Word [%, Word]*
(defun C_variables (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_Word tokens i1 v1)
            (S_variables_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'variables v0))
      )
   )
)

(defun S_variables_0 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "," i2 v2 nil)
         (C_Word tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;!multiassignment := %[ variables %]
(defun C_multiassignment (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 nil)
            (C_variables tokens i1 v1)
            (compare tokens "]" i1 v1 nil)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'multiassignment v0))
      )
   )
)

;!arguments := computing [%, computing]*
(defun C_arguments (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_computing tokens i1 v1)
            (S_arguments_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'arguments v0))
      )
   )
)

(defun S_arguments_0 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "," i2 v2 nil)
         (C_computing tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;!callmethod := %. Word %( ;2 [computing [%, computing]*]? %)
(defun C_callmethod (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "." i1 v1 nil)
            (C_Word tokens i1 v1)
            (compare tokens "(" i1 v1 nil)
            (push error_id 2)
            (if (and
                  (O_callmethod_1 tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'callmethod v0))
      )
   )
)

(defun S_callmethod_0 (tokens i2 vp)
   (setq v ())
   (while (and
         (setq i3 (clone i2))
         (setq v3 ())
         (compare tokens "," i3 v3 nil)
         (C_computing tokens i3 v3)
         (set@ i2 0 (car i3))
         (setq v2 v3)
      )
      (nconc v v2)
   )
   (check v
      (nconc vp v)
   )
   true)

(defun O_callmethod_1 (tokens i1 vp)
   (setq v1 ())
   (check (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_computing tokens i2 v2)
         (S_callmethod_0 tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc vp v1)
   )
   true)

;callinterval := %[ computing? %: ;10 computing? %]
(defun C_callinterval (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 true)
            (O_callinterval_0 tokens i1 v1)
            (compare tokens ":" i1 v1 true)
            (push error_id 10)
            (if (and
                  (O_callinterval_1 tokens i1 v1)
                  (compare tokens "]" i1 v1 true)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'callinterval v0))
      )
   )
)

(defun O_callinterval_0 (tokens i1 vp)
   (setq v1 ())
   (check (C_computing tokens i1 v1)
      (nconc vp v1)
   )
   true)

(defun O_callinterval_1 (tokens i1 vp)
   (setq v1 ())
   (check (C_computing tokens i1 v1)
      (nconc vp v1)
   )
   true)

;!callindexes := %[ ;1 computing [%, computing]* %]
(defun C_callindexes (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 nil)
            (push error_id 1)
            (if (and
                  (C_computing tokens i1 v1)
                  (S_callindexes_0 tokens i1 v1)
                  (compare tokens "]" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'callindexes v0))
      )
   )
)

(defun S_callindexes_0 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "," i2 v2 nil)
         (C_computing tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;call := [lambda^Word] %( arguments? %) [callinterval^callindexes^callmethod]*
(defun C_call (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or (C_λ tokens i1 v1) (C_Word tokens i1 v1))
            (compare tokens "(" i1 v1 true)
            (O_call_0 tokens i1 v1)
            (compare tokens ")" i1 v1 true)
            (S_call_1 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'call v0))
      )
   )
)

(defun O_call_0 (tokens i1 vp)
   (setq v1 ())
   (check (C_arguments tokens i1 v1)
      (nconc vp v1)
   )
   true)

(defun S_call_1 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (while (or (C_callinterval tokens i1 v1) (C_callindexes tokens i1 v1) (C_callmethod tokens i1 v1))
      (nconc v v1)
      (setq v1 ())
   )
   (check v
      (nconc vp v)
   )
   true)

;method := variable callmethod [callinterval^callindexes^callmethod]*
(defun C_method (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_variable tokens i1 v1)
            (C_callmethod tokens i1 v1)
            (S_method_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'method v0))
      )
   )
)

(defun S_method_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (while (or (C_callinterval tokens i1 v1) (C_callindexes tokens i1 v1) (C_callmethod tokens i1 v1))
      (nconc v v1)
      (setq v1 ())
   )
   (check v
      (nconc vp v)
   )
   true)

;catching := [$Except^$Catch] [%( Word %)]? expressions+
(defun C_catching (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (compare tokens "Except" i1 v1 true)
               (compare tokens "Catch" i1 v1 true)
            )
            (O_catching_0 tokens i1 v1)
            (P_catching_1 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'catching v0))
      )
   )
)

(defun O_catching_0 (tokens i1 vp)
   (setq v1 ())
   (check (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "(" i2 v2 true)
         (C_Word tokens i2 v2)
         (compare tokens ")" i2 v2 true)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc vp v1)
   )
   true)

(defun P_catching_1 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!amaybe := $Try ;15  expressions+ catching $EndTry
(defun C_amaybe (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Try" i1 v1 nil)
            (push error_id 15)
            (if (and
                  (P_amaybe_0 tokens i1 v1)
                  (C_catching tokens i1 v1)
                  (compare tokens "EndTry" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'amaybe v0))
      )
   )
)

(defun P_amaybe_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!assignmenttopself :=  selfvariable operatorop computing
(defun C_assignmenttopself (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_selfvariable tokens i1 v1)
            (C_operatorop tokens i1 v1)
            (C_computing tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'assignmenttopself v0))
      )
   )
)

;!assignmentself :=  selfvariable %= computing
(defun C_assignmentself (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_selfvariable tokens i1 v1)
            (compare tokens "=" i1 v1 nil)
            (C_computing tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'assignmentself v0))
      )
   )
)

;!assignmentop :=  variable operatorop computing
(defun C_assignmentop (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_variable tokens i1 v1)
            (C_operatorop tokens i1 v1)
            (C_computing tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'assignmentop v0))
      )
   )
)

;!assignment := [multiassignment^variable] %= computing
(defun C_assignment (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (C_multiassignment tokens i1 v1)
               (C_variable tokens i1 v1)
            )
            (compare tokens "=" i1 v1 nil)
            (C_computing tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'assignment v0))
      )
   )
)

;!assignmentg := [multiassignment^variable] %= %: computing
(defun C_assignmentg (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (C_multiassignment tokens i1 v1)
               (C_variable tokens i1 v1)
            )
            (compare tokens "=" i1 v1 nil)
            (compare tokens ":" i1 v1 nil)
            (C_computing tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'assignmentg v0))
      )
   )
)

;!walrus := Word %: %=  computing
(defun C_walrus (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_Word tokens i1 v1)
            (compare tokens ":" i1 v1 nil)
            (compare tokens "=" i1 v1 nil)
            (C_computing tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'walrus v0))
      )
   )
)

;!parenthetic := %( computing %)
(defun C_parenthetic (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "(" i1 v1 nil)
            (C_computing tokens i1 v1)
            (compare tokens ")" i1 v1 nil)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'parenthetic v0))
      )
   )
)

;!tojoin := [variable^astring] %. Pythonjoin ;13 %( computing %)
(defun C_tojoin (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (C_variable tokens i1 v1)
               (C_astring tokens i1 v1)
            )
            (compare tokens "." i1 v1 nil)
            (C_Pythonjoin tokens i1 v1)
            (push error_id 13)
            (if (and
                  (compare tokens "(" i1 v1 nil)
                  (C_computing tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'tojoin v0))
      )
   )
)

;^callitem := lispe^walrus^tojoin^call^lambda^comprehension^selfvariable^method^valuelist^valuedictionary^parenthetic^astring^minus^anumber^returning^variable
(defun C_callitem (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (C_lispe tokens i0 v0)
            (C_walrus tokens i0 v0)
            (C_tojoin tokens i0 v0)
            (C_call tokens i0 v0)
            (C_λ tokens i0 v0)
            (C_comprehension tokens i0 v0)
            (C_selfvariable tokens i0 v0)
            (C_method tokens i0 v0)
            (C_valuelist tokens i0 v0)
            (C_valuedictionary tokens i0 v0)
            (C_parenthetic tokens i0 v0)
            (C_astring tokens i0 v0)
            (C_minus tokens i0 v0)
            (C_anumber tokens i0 v0)
            (C_returning tokens i0 v0)
            (C_variable tokens i0 v0)
         )
         (nconc v v0)
      )
   )
)

;&computing := callitem  [operator callitem]*
(defun C_computing (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_callitem tokens i1 v1)
            (S_computing_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (if (eq (size v0) 1)
            (nconc v v0)
            (push v (cons 'computing v0))
         )
      )
   )
)

(defun S_computing_0 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_operator tokens i2 v2)
         (C_callitem tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;!multiop := Word computing [%, computing]*
(defun C_multiop (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_Word tokens i1 v1)
            (C_computing tokens i1 v1)
            (S_multiop_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'multiop v0))
      )
   )
)

(defun S_multiop_0 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "," i2 v2 nil)
         (C_computing tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;body := predicates+
(defun C_body (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (P_body_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'body v0))
      )
   )
)

(defun P_body_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_predicates tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_predicates tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;returning := [$return^$break] computing?
(defun C_returning (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (compare tokens "return" i1 v1 true)
               (compare tokens "break" i1 v1 true)
            )
            (O_returning_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'returning v0))
      )
   )
)

(defun O_returning_0 (tokens i1 vp)
   (setq v1 ())
   (check (C_computing tokens i1 v1)
      (nconc vp v1)
   )
   true)

;^expressions := lispe^assignmenttopself^assignmentself^assignmentop^assignmentg^assignment^switch^amaybe^forin^for^if^while^multiop^computing
(defun C_expressions (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (C_lispe tokens i0 v0)
            (C_assignmenttopself tokens i0 v0)
            (C_assignmentself tokens i0 v0)
            (C_assignmentop tokens i0 v0)
            (C_assignmentg tokens i0 v0)
            (C_assignment tokens i0 v0)
            (C_switch tokens i0 v0)
            (C_amaybe tokens i0 v0)
            (C_forin tokens i0 v0)
            (C_for tokens i0 v0)
            (C_if tokens i0 v0)
            (C_while tokens i0 v0)
            (C_multiop tokens i0 v0)
            (C_computing tokens i0 v0)
         )
         (nconc v v0)
      )
   )
)

;^predicates := lispe^assignmenttopself^assignmentself^assignmentself^assignmentop^assignmentg^assignment^comparisonmax^switch^amaybe^forin^for^if^while^multiop^computing
(defun C_predicates (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (C_lispe tokens i0 v0)
            (C_assignmenttopself tokens i0 v0)
            (C_assignmentself tokens i0 v0)
            (C_assignmentself tokens i0 v0)
            (C_assignmentop tokens i0 v0)
            (C_assignmentg tokens i0 v0)
            (C_assignment tokens i0 v0)
            (C_comparisonmax tokens i0 v0)
            (C_switch tokens i0 v0)
            (C_amaybe tokens i0 v0)
            (C_forin tokens i0 v0)
            (C_for tokens i0 v0)
            (C_if tokens i0 v0)
            (C_while tokens i0 v0)
            (C_multiop tokens i0 v0)
            (C_computing tokens i0 v0)
         )
         (nconc v v0)
      )
   )
)

;!classedef := $Class Word ;16 classfunc+ $EndClass
(defun C_classedef (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Class" i1 v1 nil)
            (C_Word tokens i1 v1)
            (push error_id 16)
            (if (and
                  (P_classedef_0 tokens i1 v1)
                  (compare tokens "EndClass" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'classedef v0))
      )
   )
)

(defun P_classedef_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_classfunc tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_classfunc tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!classfunc := [$Function^$Def] Word %( $Self %, ;4 variables? %) expressions+ [$EndFunction^$EndDef] 
(defun C_classfunc (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (compare tokens "Function" i1 v1 nil)
               (compare tokens "Def" i1 v1 nil)
            )
            (C_Word tokens i1 v1)
            (compare tokens "(" i1 v1 nil)
            (compare tokens "Self" i1 v1 nil)
            (compare tokens "," i1 v1 nil)
            (push error_id 4)
            (if (and
                  (O_classfunc_0 tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
                  (P_classfunc_1 tokens i1 v1)
                  (or
                     (compare tokens "EndFunction" i1 v1 nil)
                     (compare tokens "EndDef" i1 v1 nil)
                  )
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'classfunc v0))
      )
   )
)

(defun O_classfunc_0 (tokens i1 vp)
   (setq v1 ())
   (check (C_variables tokens i1 v1)
      (nconc vp v1)
   )
   true)

(defun P_classfunc_1 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!then := $Then? expressions+
(defun C_then (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (O_then_0 tokens i1 v1)
            (P_then_1 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'then v0))
      )
   )
)

(defun O_then_0 (tokens i1 vp)
   (setq v1 ())
   (check (compare tokens "Then" i1 v1 nil)
      (nconc vp v1)
   )
   true)

(defun P_then_1 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!else := $Else expressions+
(defun C_else (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Else" i1 v1 nil)
            (P_else_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'else v0))
      )
   )
)

(defun P_else_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!tail := %$ variable
(defun C_tail (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "$" i1 v1 nil)
            (C_variable tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'tail v0))
      )
   )
)

;!patternlist := %[ ;3 [ pattern [%, pattern]* tail? ]? %]
(defun C_patternlist (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 nil)
            (push error_id 3)
            (if (and
                  (O_patternlist_2 tokens i1 v1)
                  (compare tokens "]" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'patternlist v0))
      )
   )
)

(defun S_patternlist_0 (tokens i2 vp)
   (setq v ())
   (while (and
         (setq i3 (clone i2))
         (setq v3 ())
         (compare tokens "," i3 v3 nil)
         (C_pattern tokens i3 v3)
         (set@ i2 0 (car i3))
         (setq v2 v3)
      )
      (nconc v v2)
   )
   (check v
      (nconc vp v)
   )
   true)

(defun O_patternlist_1 (tokens i2 vp)
   (setq v2 ())
   (check (C_tail tokens i2 v2)
      (nconc vp v2)
   )
   true)

(defun O_patternlist_2 (tokens i1 vp)
   (setq v1 ())
   (check (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_pattern tokens i2 v2)
         (S_patternlist_0 tokens i2 v2)
         (O_patternlist_1 tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc vp v1)
   )
   true)

;!itempattern := [astring^minus^anumber^variable] %: pattern
(defun C_itempattern (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (C_astring tokens i1 v1)
               (C_minus tokens i1 v1)
               (C_anumber tokens i1 v1)
               (C_variable tokens i1 v1)
            )
            (compare tokens ":" i1 v1 nil)
            (C_pattern tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'itempattern v0))
      )
   )
)

;!patterndictionary := %{ ;11 [itempattern [%, itempattern]* tail? ]? %}
(defun C_patterndictionary (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "{" i1 v1 nil)
            (push error_id 11)
            (if (and
                  (O_patterndictionary_2 tokens i1 v1)
                  (compare tokens "}" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'patterndictionary v0))
      )
   )
)

(defun S_patterndictionary_0 (tokens i2 vp)
   (setq v ())
   (while (and
         (setq i3 (clone i2))
         (setq v3 ())
         (compare tokens "," i3 v3 nil)
         (C_itempattern tokens i3 v3)
         (set@ i2 0 (car i3))
         (setq v2 v3)
      )
      (nconc v v2)
   )
   (check v
      (nconc vp v)
   )
   true)

(defun O_patterndictionary_1 (tokens i2 vp)
   (setq v2 ())
   (check (C_tail tokens i2 v2)
      (nconc vp v2)
   )
   true)

(defun O_patterndictionary_2 (tokens i1 vp)
   (setq v1 ())
   (check (and
         (setq i2 (clone i1))
         (setq v2 ())
         (C_itempattern tokens i2 v2)
         (S_patterndictionary_0 tokens i2 v2)
         (O_patterndictionary_1 tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc vp v1)
   )
   true)

;pattern := patternlist^patterndictionary^astring^minus^anumber^variable
(defun C_pattern (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (or
            (C_patternlist tokens i0 v0)
            (C_patterndictionary tokens i0 v0)
            (C_astring tokens i0 v0)
            (C_minus tokens i0 v0)
            (C_anumber tokens i0 v0)
            (C_variable tokens i0 v0)
         )
         (push v (cons 'pattern v0))
      )
   )
)

;!patterns := pattern [%, pattern]*
(defun C_patterns (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_pattern tokens i1 v1)
            (S_patterns_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'patterns v0))
      )
   )
)

(defun S_patterns_0 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "," i2 v2 nil)
         (C_pattern tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;!patternsjs := Word [%, pattern]*
(defun C_patternsjs (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (C_Word tokens i1 v1)
            (S_patternsjs_0 tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'patternsjs v0))
      )
   )
)

(defun S_patternsjs_0 (tokens i1 vp)
   (setq v ())
   (while (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "," i2 v2 nil)
         (C_pattern tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc v v1)
   )
   (check v
      (nconc vp v)
   )
   true)

;!parameters := %( ;4 variables? %)
(defun C_parameters (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "(" i1 v1 nil)
            (push error_id 4)
            (if (and
                  (O_parameters_0 tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'parameters v0))
      )
   )
)

(defun O_parameters_0 (tokens i1 vp)
   (setq v1 ())
   (check (C_variables tokens i1 v1)
      (nconc vp v1)
   )
   true)

;!function := [$Function^$Def] Word parameters expressions+ [$EndFunction^$EndDef]
(defun C_function (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (compare tokens "Function" i1 v1 nil)
               (compare tokens "Def" i1 v1 nil)
            )
            (C_Word tokens i1 v1)
            (C_parameters tokens i1 v1)
            (P_function_0 tokens i1 v1)
            (or
               (compare tokens "EndFunction" i1 v1 nil)
               (compare tokens "EndDef" i1 v1 nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'function v0))
      )
   )
)

(defun P_function_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!rule := $Rule Word %( ;4 patterns %) predicates+ $EndRule
(defun C_rule (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Rule" i1 v1 nil)
            (C_Word tokens i1 v1)
            (compare tokens "(" i1 v1 nil)
            (push error_id 4)
            (if (and
                  (C_patterns tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
                  (P_rule_0 tokens i1 v1)
                  (compare tokens "EndRule" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'rule v0))
      )
   )
)

(defun P_rule_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_predicates tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_predicates tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!patternrule := $Pattern Word %( ;4 patterns %) predicates+ $EndPattern
(defun C_patternrule (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Pattern" i1 v1 nil)
            (C_Word tokens i1 v1)
            (compare tokens "(" i1 v1 nil)
            (push error_id 4)
            (if (and
                  (C_patterns tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
                  (P_patternrule_0 tokens i1 v1)
                  (compare tokens "EndPattern" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'patternrule v0))
      )
   )
)

(defun P_patternrule_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_predicates tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_predicates tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!jsfunc := [$FunctionJS^$DefJs] Word %( ;4 variables %) expressions+ [$EndFunctionJS^$EndDefJs]
(defun C_jsfunc (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (or
               (compare tokens "FunctionJS" i1 v1 nil)
               (compare tokens "DefJs" i1 v1 nil)
            )
            (C_Word tokens i1 v1)
            (compare tokens "(" i1 v1 nil)
            (push error_id 4)
            (if (and
                  (C_variables tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
                  (P_jsfunc_0 tokens i1 v1)
                  (or
                     (compare tokens "EndFunctionJS" i1 v1 nil)
                     (compare tokens "EndDefJs" i1 v1 nil)
                  )
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'jsfunc v0))
      )
   )
)

(defun P_jsfunc_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!jsrule := $RuleJs Word %( ;4 patternsjs %) predicates+ $EndRuleJS
(defun C_jsrule (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "RuleJs" i1 v1 nil)
            (C_Word tokens i1 v1)
            (compare tokens "(" i1 v1 nil)
            (push error_id 4)
            (if (and
                  (C_patternsjs tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
                  (P_jsrule_0 tokens i1 v1)
                  (compare tokens "EndRuleJS" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'jsrule v0))
      )
   )
)

(defun P_jsrule_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_predicates tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_predicates tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!jspatternrule := $Patternjs Word %( ;4 patternsjs %) predicates+ $EndPatternJS
(defun C_jspatternrule (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Patternjs" i1 v1 nil)
            (C_Word tokens i1 v1)
            (compare tokens "(" i1 v1 nil)
            (push error_id 4)
            (if (and
                  (C_patternsjs tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
                  (P_jspatternrule_0 tokens i1 v1)
                  (compare tokens "EndPatternJS" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'jspatternrule v0))
      )
   )
)

(defun P_jspatternrule_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_predicates tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_predicates tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!athread := $Thread Word parameters expressions+ $EndThread
(defun C_athread (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Thread" i1 v1 nil)
            (C_Word tokens i1 v1)
            (C_parameters tokens i1 v1)
            (P_athread_0 tokens i1 v1)
            (compare tokens "EndThread" i1 v1 nil)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'athread v0))
      )
   )
)

(defun P_athread_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!lambda := %[ [$lambda^$λ] ;17 %( variables? %) body %]
(defun C_λ (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 nil)
            (or
               (compare tokens "lambda" i1 v1 nil)
               (compare tokens "λ" i1 v1 nil)
            )
            (push error_id 17)
            (if (and
                  (compare tokens "(" i1 v1 nil)
                  (O_λ_0 tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
                  (C_body tokens i1 v1)
                  (compare tokens "]" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'λ v0))
      )
   )
)

(defun O_λ_0 (tokens i1 vp)
   (setq v1 ())
   (check (C_variables tokens i1 v1)
      (nconc vp v1)
   )
   true)

;!comprehension := %[ computing $For ;12 Word $in computing [$If comparison]? %] 
(defun C_comprehension (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "[" i1 v1 nil)
            (C_computing tokens i1 v1)
            (compare tokens "For" i1 v1 nil)
            (push error_id 12)
            (if (and
                  (C_Word tokens i1 v1)
                  (compare tokens "in" i1 v1 nil)
                  (C_computing tokens i1 v1)
                  (O_comprehension_0 tokens i1 v1)
                  (compare tokens "]" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'comprehension v0))
      )
   )
)

(defun O_comprehension_0 (tokens i1 vp)
   (setq v1 ())
   (check (and
         (setq i2 (clone i1))
         (setq v2 ())
         (compare tokens "If" i2 v2 nil)
         (C_comparison tokens i2 v2)
         (set@ i1 0 (car i2))
         (setq v1 v2)
      )
      (nconc vp v1)
   )
   true)

;!elif := $Elif ;5 comparison then [elif^else]?
(defun C_elif (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Elif" i1 v1 nil)
            (push error_id 5)
            (if (and
                  (C_comparison tokens i1 v1)
                  (C_then tokens i1 v1)
                  (O_elif_0 tokens i1 v1)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'elif v0))
      )
   )
)

(defun O_elif_0 (tokens i1 vp)
   (setq v1 ())
   (check (or (C_elif tokens i1 v1) (C_else tokens i1 v1))
      (nconc vp v1)
   )
   true)

;!if := $If ;5 comparison then [elif^else]? $EndIf
(defun C_if (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "If" i1 v1 nil)
            (push error_id 5)
            (if (and
                  (C_comparison tokens i1 v1)
                  (C_then tokens i1 v1)
                  (O_if_0 tokens i1 v1)
                  (compare tokens "EndIf" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'if v0))
      )
   )
)

(defun O_if_0 (tokens i1 vp)
   (setq v1 ())
   (check (or (C_elif tokens i1 v1) (C_else tokens i1 v1))
      (nconc vp v1)
   )
   true)

;!while := $While ;6 comparison expressions+ $EndWhile
(defun C_while (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "While" i1 v1 nil)
            (push error_id 6)
            (if (and
                  (C_comparison tokens i1 v1)
                  (P_while_0 tokens i1 v1)
                  (compare tokens "EndWhile" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'while v0))
      )
   )
)

(defun P_while_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!forin := $For variable $in ;7 callitem expressions+ $EndFor
(defun C_forin (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "For" i1 v1 nil)
            (C_variable tokens i1 v1)
            (compare tokens "in" i1 v1 nil)
            (push error_id 7)
            (if (and
                  (C_callitem tokens i1 v1)
                  (P_forin_0 tokens i1 v1)
                  (compare tokens "EndFor" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'forin v0))
      )
   )
)

(defun P_forin_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!for := $For ;8 assignment %, comparison %, assignment expressions+ $EndFor
(defun C_for (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "For" i1 v1 nil)
            (push error_id 8)
            (if (and
                  (C_assignment tokens i1 v1)
                  (compare tokens "," i1 v1 nil)
                  (C_comparison tokens i1 v1)
                  (compare tokens "," i1 v1 nil)
                  (C_assignment tokens i1 v1)
                  (P_for_0 tokens i1 v1)
                  (compare tokens "EndFor" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'for v0))
      )
   )
)

(defun P_for_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_expressions tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_expressions tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)

;!acase := $case astring %: expressions
(defun C_acase (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "case" i1 v1 nil)
            (C_astring tokens i1 v1)
            (compare tokens ":" i1 v1 nil)
            (C_expressions tokens i1 v1)
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'acase v0))
      )
   )
)

;!switch := $Switch ;14 %( variable %) acase+ $EndSwitch
(defun C_switch (tokens i0 v)
   (check (and do_not_stop (< (car i0) (size tokens)))
      (setq v0 ())
      (if (and
            (setq i1 (clone i0))
            (setq v1 ())
            (compare tokens "Switch" i1 v1 nil)
            (push error_id 14)
            (if (and
                  (compare tokens "(" i1 v1 nil)
                  (C_variable tokens i1 v1)
                  (compare tokens ")" i1 v1 nil)
                  (P_switch_0 tokens i1 v1)
                  (compare tokens "EndSwitch" i1 v1 nil)
               )
               (pop error_id)
               (setg do_not_stop nil)
            )
            (set@ i0 0 (car i1))
            (setq v0 v1)
         )
         (push v (cons 'switch v0))
      )
   )
)

(defun P_switch_0 (tokens i1 vp)
   (setq v ())
   (setq v1 ())
   (check (C_acase tokens i1 v1)
      (push v v1)
      (setq v1 ())
      (while (C_acase tokens i1 v1) (nconc v v1) (setq v1 ()))
   )
   (if v
      (nconc vp v)
   )
)


(defun nokeywords(w)
      (not (in  '("or" "and" "xor" "in" "eq" "neq" "not" "self" "except" "catch" "try" "endtry" "return" "break" "class" "endclass" "function" "def" "endfunction" "enddef" "then" "else" "rule" "endrule" "pattern" "endpattern" "functionjs" "defjs" "endfunctionjs" "enddefjs" "rulejs" "endrulejs" "patternjs" "endpatternjs" "thread" "endthread" "lambda" "λ" "for" "if" "elif" "endif" "while" "endwhile" "endfor" "case" "switch" "endswitch") (lower w)))
)
   (setq error_messages {"16":"error when defining a class > > >" "15":"error when analysing a try / catch > > >" "14":"error when analysing a \"switch\" > > >" "13":"error when analysing a \"join\" ( Python style ) > > >" "12":"error when analysing a list comprehension > > >" "17":"error when analysing a lambda > > >" "10":"error when analysing an interval , you can ' t chain intervals > > >" "8":"expecting a closing tag for \"for\" > > >" "3":"expecting a closing \"]\" for \"list\" > > >" "7":"expecting a closing tag for \"forin\" > > >" "6":"expecting a closing tag for \"while\" > > >" "9":"error when analysing a method > > >" "1":"expecting a closing \"]\" > > >" "4":"expecting a closing tag for \"function\" > > >" "5":"expecting a closing tag for \"if\" > > >" "11":"error when analysing a dictionary > > >" "2":"expecting a closing \")\" for a \"method\" > > >"})
(setq parser_tok (tokenizer_rules))

(setq rg «1:{%d #A-F #a-f}
#9=#
#10=#
#32=#
`?*`=:34
f"{[\-"] ~%r}*"=34
"""?*"""=:34
'''?*'''=:34
"{[\-"] ~%r}*"=34
'~%r*'=34
0b{1 0}+=57
0x%1+(.%1+({p P}({%- %+})%d+))=57
%d+(.%d+({eE}({%- %+})%d+))=57
%o=63
%p=32
%h{%h %d}*=65
%a{%a %d @}*=65
»
)

(setq rg (replace rg "\r" ""))
(setq rg (split rg "\n"))

(set_tokenizer_rules parser_tok rg)

(defun abstract_tree (code)
   (setq code (replace code "\r" ""))
   (setg error_id '(0))
   (setg do_not_stop true)
   (key@ error_messages 0 "Syntax Error")
   ; The magic of LispE. A one-liner to get rid of lines that starts with REM
   (setq code (join (filterlist (\(x) (neq (lower (@@ (trim x) 0 4)) "rem ")) (split code "\n")) "\n"))
   (setq tokens (tokenize_rules parser_tok (+ code "\n")))
   (setq i '(0))
   (setq res (C_analyse tokens i ()))
   (setq i (car i))
   (if (< i (size tokens))
       (block
          (insert tokens "ERROR>>>" i)
	       (list (join (maplist (\(x) (@ error_messages x)) error_id) ", ") "in \"" (join (@@ tokens (if (< i 10) 0 (- i 10)) (+ 20 i)) " ") "\"")
       )
      res
   )
)

